
CREATE TABLE OCEAN_BANDE (
    BAN_ID SMALLINT UNSIGNED NOT NULL PRIMARY KEY,
    BAN_LIB VARCHAR(70) NOT NULL
);

CREATE TABLE OCEAN_BIASTEE (
    BTE_ID TINYINT UNSIGNED NOT NULL PRIMARY KEY,
    BTE_LIB VARCHAR(21) NOT NULL,
    BTE_DEF BOOLEAN NOT NULL,
    BTE_DEF_RS BOOLEAN NOT NULL
);

CREATE TABLE OCEAN_CATALIMPEXP (
    CIE_ID SMALLINT UNSIGNED NOT NULL PRIMARY KEY,
    CIE_NOM VARCHAR(30) NOT NULL,
    CIE_DESCRIPTION VARCHAR(165) NOT NULL,
    CIE_PACKAGE VARCHAR(30) NOT NULL,
    CIE_TYPE TINYINT UNSIGNED NOT NULL,
    CIE_VALID TINYINT UNSIGNED NOT NULL
);

CREATE TABLE OCEAN_CONSTRUCTEUR (
    CTR_ID TINYINT UNSIGNED NOT NULL PRIMARY KEY,
    CTR_LIB VARCHAR(15) NOT NULL,
    CTR_DEF BOOLEAN NOT NULL
);

CREATE TABLE OCEAN_DESCPARAM (
    DSC_ID MEDIUMINT UNSIGNED NOT NULL PRIMARY KEY,
    DSC_LIB VARCHAR(30) NOT NULL,
    DSC_DEF BOOLEAN NOT NULL
);

CREATE TABLE OCEAN_ENVIRONMNT (
    ENV_ID TINYINT UNSIGNED NOT NULL PRIMARY KEY,
    ENV_LIB VARCHAR(15) NOT NULL,
    ENV_DEF BOOLEAN NOT NULL
);

CREATE TABLE OCEAN_ETATDM (
    EDM_ID TINYINT UNSIGNED NOT NULL PRIMARY KEY,
    EDM_CODE VARCHAR(10) NOT NULL,
    EDM_LIB VARCHAR(20) NOT NULL,
    EDM_DEF BOOLEAN NOT NULL
);

CREATE TABLE OCEAN_ETATIE (
    EIE_ID TINYINT UNSIGNED NOT NULL PRIMARY KEY,
    EIE_LIB VARCHAR(20) NOT NULL,
    EIE_CODE VARCHAR(15) NOT NULL
);

CREATE TABLE OCEAN_ETATSW (
    ESW_ID TINYINT UNSIGNED NOT NULL PRIMARY KEY,
    ESW_CODE VARCHAR(2) NOT NULL,
    ESW_LIB VARCHAR(20) NOT NULL,
    ESW_CODECELL VARCHAR(2) NOT NULL,
    ESW_LIBCELL VARCHAR(20) NOT NULL,
    ESW_DEF BOOLEAN NOT NULL
);

CREATE TABLE OCEAN_FCTANT (
    FCA_ID TINYINT UNSIGNED NOT NULL PRIMARY KEY,
    FCA_LIB VARCHAR(10) NOT NULL,
    FCA_DEF BOOLEAN NOT NULL,
    FCA_DEF_RS BOOLEAN NOT NULL
);

CREATE TABLE OCEAN_MQANT (
    MQA_ID TINYINT UNSIGNED NOT NULL PRIMARY KEY,
    MQA_LIB VARCHAR(20) NOT NULL
);

CREATE TABLE OCEAN_OPERATORAPPLIC (
    OPP_ID TINYINT UNSIGNED NOT NULL PRIMARY KEY,
    OPP_LIB VARCHAR(3) NOT NULL,
    OPP_DEF BOOLEAN NOT NULL,
    ZP_LEADER TINYINT UNSIGNED NOT NULL,
    OPP_CODE VARCHAR(1) NOT NULL
);

CREATE TABLE OCEAN_PARAMCI (
    PCI_NOM VARCHAR(35) NOT NULL PRIMARY KEY,
    PCI_VAL MEDIUMINT NOT NULL,
    PCI_TYPE TINYINT UNSIGNED NOT NULL
);

CREATE TABLE OCEAN_PORTEEPARAM (
    PPA_ID TINYINT UNSIGNED NOT NULL PRIMARY KEY,
    PPA_LIB VARCHAR(50) NOT NULL,
    PPA_TYPOBJ VARCHAR(10) NOT NULL,
    PPA_CAT VARCHAR(25) NOT NULL
);

CREATE TABLE OCEAN_REFDITRIPLEX (
    RFD_ID SMALLINT UNSIGNED NOT NULL PRIMARY KEY,
    RFD_LIB VARCHAR(100) NOT NULL,
    RFD_DEF BOOLEAN NOT NULL,
    RFD_DEF_RS BOOLEAN NOT NULL
);

CREATE TABLE OCEAN_REFRET (
    RET_ID TINYINT UNSIGNED NOT NULL PRIMARY KEY,
    RET_LIB VARCHAR(50) NOT NULL,
    RET_DEF BOOLEAN NOT NULL
);

CREATE TABLE OCEAN_REFTMA (
    RFT_ID SMALLINT UNSIGNED NOT NULL PRIMARY KEY,
    RFT_LIB VARCHAR(50) NOT NULL,
    RFT_DEF BOOLEAN NOT NULL,
    RFT_DEF_RS BOOLEAN NOT NULL
);

CREATE TABLE OCEAN_REGION (
    REG_NUM TINYINT UNSIGNED NOT NULL PRIMARY KEY,
    REG_LIB VARCHAR(15) NOT NULL,
    REG_CODE VARCHAR(3) NOT NULL,
    REG_VIRT BOOLEAN NOT NULL
);

CREATE TABLE OCEAN_REG_DEP (
    REG_NUM TINYINT UNSIGNED NOT NULL,
    DEP_NUM TINYINT UNSIGNED NOT NULL PRIMARY KEY,

    FOREIGN KEY (REG_NUM) REFERENCES OCEAN_REGION(REG_NUM)
);

CREATE TABLE OCEAN_TECHNO (
    TEC_ID TINYINT UNSIGNED NOT NULL PRIMARY KEY,
    TEC_LIB VARCHAR(2) NOT NULL
);

CREATE TABLE OCEAN_TYPCELL (
    TPC_ID TINYINT UNSIGNED NOT NULL PRIMARY KEY,
    TPC_LIB VARCHAR(20) NOT NULL,
    TPC_DEF BOOLEAN NOT NULL,
    TPC_DEF_RS BOOLEAN NOT NULL
);

CREATE TABLE OCEAN_TYPEDEMANDE (
    TDM_ID TINYINT UNSIGNED NOT NULL PRIMARY KEY,
    TDM_LIB VARCHAR(40) NOT NULL,
    TDM_DEF BOOLEAN NOT NULL
);

CREATE TABLE OCEAN_TYPEPROJET (
    TYPEPROJET_ID TINYINT UNSIGNED NOT NULL PRIMARY KEY,
    TYPEPROJET_LIB VARCHAR(30) NOT NULL
);

CREATE TABLE OCEAN_ZONERESEAUX (
    ZRE_ID TINYINT UNSIGNED NOT NULL PRIMARY KEY,
    ZRE_LIB VARCHAR(25) NOT NULL,
    ZRE_DEF BOOLEAN NOT NULL
);

CREATE TABLE OCEAN_ZONESERVICE (
    ZSE_ID MEDIUMINT UNSIGNED NOT NULL PRIMARY KEY,
    ZSE_LIB VARCHAR(40) NOT NULL,
    ZSE_DEF BOOLEAN NOT NULL
);

CREATE TABLE OCEAN_ZONESPEC (
    ZSP_ID TINYINT UNSIGNED NOT NULL PRIMARY KEY,
    REG_NUM TINYINT UNSIGNED NOT NULL,
    ZSP_LIB VARCHAR(50) NOT NULL,
    ZSP_CODE VARCHAR(3) NOT NULL,
    ZSP_DEF BOOLEAN NOT NULL,

    FOREIGN KEY (REG_NUM) REFERENCES OCEAN_REGION(REG_NUM)
);

CREATE TABLE OCEAN_ZONEVIE (
    ZVI_ID MEDIUMINT UNSIGNED NOT NULL PRIMARY KEY,
    ZVI_LIB VARCHAR(50) NOT NULL,
    ZVI_DEF BOOLEAN NOT NULL
);

CREATE TABLE OCEAN_ATTCELLDM (
    CDM_ID TINYINT UNSIGNED NOT NULL PRIMARY KEY,
    CDM_NOM VARCHAR(30) NOT NULL
);

CREATE TABLE OCEAN_CATALANT (
    CTA_ID SMALLINT UNSIGNED NOT NULL PRIMARY KEY,
    MQA_ID TINYINT UNSIGNED NOT NULL,
    BAN_ID SMALLINT UNSIGNED NOT NULL,
    CTA_REFANT VARCHAR(30) NOT NULL,
    CTA_REFSFR VARCHAR(30) NOT NULL,
    CTA_BANDFQ VARCHAR(50) NOT NULL,
    CTA_OPLANH SMALLINT UNSIGNED NOT NULL,
    CTA_OPLANV SMALLINT UNSIGNED NOT NULL,
    CTA_ROS900 FLOAT(5,2) DEFAULT NULL,
    CTA_ROS1800 FLOAT(5,2) DEFAULT NULL,
    CTA_ROSUMTS FLOAT(5,2) DEFAULT NULL,
    CTA_ROSU900 FLOAT(5,2) DEFAULT NULL,
    CTA_GAIN900 FLOAT(5,2) DEFAULT NULL,
    CTA_GAIN1800 FLOAT(5,2) DEFAULT NULL,
    CTA_GAINUMTS FLOAT(5,2) DEFAULT NULL,
    CTA_GAINU900 FLOAT(5,2) DEFAULT NULL,
    CTA_HANT SMALLINT UNSIGNED DEFAULT NULL,
    CTA_POIDSANT FLOAT(5,2) DEFAULT 0,
    CTA_SFR900 VARCHAR(30) DEFAULT NULL,
    CTA_SFR1800 VARCHAR(30) DEFAULT NULL,
    CTA_SFRUMTS VARCHAR(30) DEFAULT NULL,
    CTA_SFRU900 VARCHAR(30) DEFAULT NULL,
    CTA_DEF BOOLEAN NOT NULL,
    CTA_DIRECT VARCHAR(15) DEFAULT NULL,
    CTA_ROSL800 FLOAT(5,2) DEFAULT NULL,
    CTA_ROSL1800 FLOAT(5,2) DEFAULT NULL,
    CTA_ROSL2600 FLOAT(5,2) DEFAULT NULL,
    CTA_GAINL800 FLOAT(5,2) DEFAULT NULL,
    CTA_GAINL1800 FLOAT(5,2) DEFAULT NULL,
    CTA_GAINL2600 FLOAT(5,2) DEFAULT NULL,
    CTA_SFRL800 VARCHAR(30) DEFAULT NULL,
    CTA_SFRL1800 VARCHAR(30) DEFAULT NULL,
    CTA_SFRL2600 VARCHAR(30) DEFAULT NULL,
    CTA_GAINL3500 FLOAT(5,2) DEFAULT NULL,
    CTA_ROSL3500 FLOAT(5,2) DEFAULT NULL,
    CTA_SFRL3500 VARCHAR(30) DEFAULT NULL,
    CTA_GAINL700 FLOAT(5,2) DEFAULT NULL,
    CTA_ROSL700 FLOAT(5,2) DEFAULT NULL,
    CTA_SFRL700 VARCHAR(30) DEFAULT NULL,
    CTA_GAINL1500 FLOAT(5,2) DEFAULT NULL,
    CTA_ROSL1500 FLOAT(5,2) DEFAULT NULL,
    CTA_SFRL1500 VARCHAR(30) DEFAULT NULL,
    CTA_GAINL2100 FLOAT(5,2) DEFAULT NULL,
    CTA_ROSL2100 FLOAT(5,2) DEFAULT NULL,
    CTA_SFRL2100 VARCHAR(30) DEFAULT NULL,

    FOREIGN KEY (MQA_ID) REFERENCES OCEAN_MQANT(MQA_ID),
    FOREIGN KEY (BAN_ID) REFERENCES OCEAN_BANDE(BAN_ID)
);

CREATE TABLE OCEAN_SYSTEME (
    SYS_ID TINYINT UNSIGNED NOT NULL PRIMARY KEY,
    TEC_ID TINYINT UNSIGNED NOT NULL,
    SYS_LIB VARCHAR(5) NOT NULL,
    SYS_DESC VARCHAR(7) NOT NULL,
    SYS_CODE VARCHAR(3) NOT NULL,

    FOREIGN KEY (TEC_ID) REFERENCES OCEAN_TECHNO(TEC_ID)
);

CREATE TABLE OCEAN_BAN_SYS (
    SYS_ID TINYINT UNSIGNED NOT NULL,
    BAN_ID SMALLINT UNSIGNED NOT NULL,

    PRIMARY KEY(SYS_ID, BAN_ID),
    FOREIGN KEY (SYS_ID) REFERENCES OCEAN_SYSTEME(SYS_ID),
    FOREIGN KEY (BAN_ID) REFERENCES OCEAN_BANDE(BAN_ID)
);

CREATE TABLE OCEAN_CATALBAIE (
    CTB_ID SMALLINT UNSIGNED NOT NULL PRIMARY KEY,
    CTR_ID TINYINT UNSIGNED NOT NULL,
    BAN_ID SMALLINT UNSIGNED NOT NULL,
    CTB_REF VARCHAR(40) NOT NULL,
    CTB_POWER VARCHAR(5) NOT NULL,
    CTB_DEF BOOLEAN NOT NULL,
    RS_FLAG TINYINT UNSIGNED NOT NULL,
    MONO TINYINT UNSIGNED DEFAULT NULL,

    FOREIGN KEY (CTR_ID) REFERENCES OCEAN_CONSTRUCTEUR(CTR_ID),
    FOREIGN KEY (BAN_ID) REFERENCES OCEAN_BANDE(BAN_ID)
);

CREATE TABLE OCEAN_CATALREP (
    CRE_ID SMALLINT UNSIGNED NOT NULL PRIMARY KEY,
    BAN_ID SMALLINT UNSIGNED NOT NULL,
    CRE_REF VARCHAR(20) NOT NULL,
    CRE_FOURN VARCHAR(10) NOT NULL,
    CRE_TYPE VARCHAR(21) NOT NULL,
    CRE_NATURE VARCHAR(15) NOT NULL,
    CRE_GENRE VARCHAR(10) NOT NULL,
    CRE_GAIN900 FLOAT(5,2) DEFAULT NULL,
    CRE_GAIN1800 FLOAT(5,2) DEFAULT NULL,
    CRE_GAINUMTS FLOAT(5,2) DEFAULT NULL,
    CRE_GAINU900 FLOAT(5,2) DEFAULT NULL,
    CRE_POUT900 TINYINT UNSIGNED DEFAULT NULL,
    CRE_POUT1800 TINYINT UNSIGNED DEFAULT NULL,
    CRE_POUTUMTS TINYINT UNSIGNED DEFAULT NULL,
    CRE_POUTU900 TINYINT UNSIGNED DEFAULT NULL,
    CRE_DEF BOOLEAN NOT NULL,
    CRE_PROPA_DELAY FLOAT(5,2) DEFAULT NULL,
    CRE_GAINL800 FLOAT(5,2) DEFAULT NULL,
    CRE_GAINL1800 FLOAT(5,2) DEFAULT NULL,
    CRE_GAINL2600 FLOAT(5,2) DEFAULT NULL,
    CRE_POUTL800 TINYINT UNSIGNED DEFAULT NULL,
    CRE_POUTL1800 TINYINT UNSIGNED DEFAULT NULL,
    CRE_POUTL2600 TINYINT UNSIGNED DEFAULT NULL,
    CRE_GAINL3500 FLOAT(5,2) DEFAULT NULL,
    CRE_POUTL3500 TINYINT UNSIGNED DEFAULT NULL,
    CRE_GAINL700 FLOAT(5,2) DEFAULT NULL,
    CRE_POUTL700 TINYINT UNSIGNED DEFAULT NULL,
    CRE_GAINL1500 FLOAT(5,2) DEFAULT NULL,
    CRE_POUTL1500 TINYINT UNSIGNED DEFAULT NULL,
    CRE_GAINL2100 FLOAT(5,2) DEFAULT NULL,
    CRE_POUTL2100 TINYINT UNSIGNED DEFAULT NULL,

    FOREIGN KEY (BAN_ID) REFERENCES OCEAN_BANDE(BAN_ID)
);

CREATE TABLE OCEAN_COMBINER (
    COM_ID SMALLINT UNSIGNED NOT NULL PRIMARY KEY,
    CTR_ID TINYINT UNSIGNED NOT NULL,
    COM_LIB VARCHAR(20) NOT NULL,
    COM_DEF BOOLEAN NOT NULL,

    FOREIGN KEY (CTR_ID) REFERENCES OCEAN_CONSTRUCTEUR(CTR_ID)
);

CREATE TABLE OCEAN_CONFCHANNELELEM (
    CHE_ID SMALLINT UNSIGNED NOT NULL PRIMARY KEY,
    CTR_ID TINYINT UNSIGNED NOT NULL,
    CHE_CONF VARCHAR(55) NOT NULL,
    CHE_REPART VARCHAR(10) NOT NULL,
    CHE_NBCE SMALLINT UNSIGNED NOT NULL,
    CHE_NBCECART VARCHAR(30) NOT NULL,
    CHE_INFO VARCHAR(50) NOT NULL,
    CHE_DEF BOOLEAN NOT NULL,

    FOREIGN KEY (CTR_ID) REFERENCES OCEAN_CONSTRUCTEUR(CTR_ID)
);

CREATE TABLE OCEAN_CONFPUISSANCE (
    PUI_ID SMALLINT UNSIGNED NOT NULL PRIMARY KEY,
    CTR_ID TINYINT UNSIGNED NOT NULL,
    PUI_LIB VARCHAR(20) NOT NULL,
    PUI_DEF BOOLEAN NOT NULL,

    FOREIGN KEY (CTR_ID) REFERENCES OCEAN_CONSTRUCTEUR(CTR_ID)
);

CREATE TABLE OCEAN_FREQUENCE3G (
    F3G_ID TINYINT UNSIGNED NOT NULL PRIMARY KEY,
    F3G_FREQ SMALLINT UNSIGNED NOT NULL,
    F3G_FLGDEF BOOLEAN NOT NULL,
    F3G_PORTEUSE TINYINT UNSIGNED NOT NULL,
    SYS_ID TINYINT UNSIGNED NOT NULL,

    FOREIGN KEY (SYS_ID) REFERENCES OCEAN_SYSTEME(SYS_ID)
);

CREATE TABLE OCEAN_FREQUENCE4G (
    F4G_ID TINYINT UNSIGNED NOT NULL PRIMARY KEY,
    F4G_FREQ MEDIUMINT UNSIGNED NOT NULL,
    SYS_ID TINYINT UNSIGNED NOT NULL,
    F4G_FLGDEF BOOLEAN NOT NULL,

    FOREIGN KEY (SYS_ID) REFERENCES OCEAN_SYSTEME(SYS_ID)
);

CREATE TABLE OCEAN_GRPPARAM (
    GPR_ID SMALLINT UNSIGNED NOT NULL PRIMARY KEY,
    GPR_LIB VARCHAR(50) NOT NULL,
    GPR_DEF BOOLEAN NOT NULL
);

CREATE TABLE OCEAN_JEUPARAMHISTO (
    JPH_ID MEDIUMINT UNSIGNED NOT NULL PRIMARY KEY,
    JPH_TYPE VARCHAR(25) NOT NULL,
    JPH_MODAVT VARCHAR(30) NOT NULL,
    JPH_MODAPR VARCHAR(30) NOT NULL
);

CREATE TABLE OCEAN_MODBBU (
    BBU_ID SMALLINT UNSIGNED NOT NULL PRIMARY KEY,
    CTR_ID TINYINT UNSIGNED NOT NULL,
    BBU_REF VARCHAR(50) NOT NULL,
    BBU_DEF BOOLEAN NOT NULL,
    TEC_ID TINYINT UNSIGNED NOT NULL,
    BBU_DEF_RS BOOLEAN NOT NULL,
    TRANS VARCHAR(30) NOT NULL,

    FOREIGN KEY (CTR_ID) REFERENCES OCEAN_CONSTRUCTEUR(CTR_ID),
    FOREIGN KEY (TEC_ID) REFERENCES OCEAN_TECHNO(TEC_ID)
);

CREATE TABLE OCEAN_MODRADIO (
    MRAD_ID SMALLINT UNSIGNED NOT NULL PRIMARY KEY,
    CTR_ID TINYINT UNSIGNED NOT NULL,
    MRAD_REF VARCHAR(50) NOT NULL,
    MRAD_DEF BOOLEAN NOT NULL,
    SYS_ID TINYINT UNSIGNED NOT NULL,

    FOREIGN KEY (CTR_ID) REFERENCES OCEAN_CONSTRUCTEUR(CTR_ID),
    FOREIGN KEY (SYS_ID) REFERENCES OCEAN_SYSTEME(SYS_ID)
);

CREATE TABLE OCEAN_NATURE (
    NAT_ID SMALLINT UNSIGNED NOT NULL PRIMARY KEY,
    CTB_ID SMALLINT UNSIGNED NOT NULL,
    NAT_NOM VARCHAR(20) NOT NULL,
    NAT_DEF BOOLEAN NOT NULL,

    FOREIGN KEY (CTB_ID) REFERENCES OCEAN_CATALBAIE(CTB_ID)
);

CREATE TABLE OCEAN_PALIER (
    PAL_ID SMALLINT UNSIGNED NOT NULL PRIMARY KEY,
    TEC_ID TINYINT UNSIGNED NOT NULL,
    CTR_ID TINYINT UNSIGNED NOT NULL,
    PAL_LIB VARCHAR(20) NOT NULL,
    PAL_DEF BOOLEAN NOT NULL,

    FOREIGN KEY (TEC_ID) REFERENCES OCEAN_TECHNO(TEC_ID),
    FOREIGN KEY (CTR_ID) REFERENCES OCEAN_CONSTRUCTEUR(CTR_ID)
);

CREATE TABLE OCEAN_REF_CELL_ATTRIBUT (
    ATT_ID TINYINT UNSIGNED NOT NULL PRIMARY KEY,
    ATT_LIB VARCHAR(30) NOT NULL,
    CTR_ID TINYINT UNSIGNED NOT NULL,
    TEC_ID TINYINT UNSIGNED NOT NULL,
    ATT_TYPE VARCHAR(10) NOT NULL,
    DEF_VALUE VARCHAR(10) NOT NULL,
    ATT_RANG TINYINT UNSIGNED NOT NULL,
    ATT_ACTIF BOOLEAN NOT NULL,
    DM_IMPACT BOOLEAN NOT NULL,

    FOREIGN KEY (CTR_ID) REFERENCES OCEAN_CONSTRUCTEUR(CTR_ID),
    FOREIGN KEY (TEC_ID) REFERENCES OCEAN_TECHNO(TEC_ID)
);

CREATE TABLE OCEAN_SAUTFRQ (
    SFQ_ID TINYINT UNSIGNED NOT NULL PRIMARY KEY,
    SFQ_LIB VARCHAR(25) NOT NULL,
    SFQ_DEF BOOLEAN NOT NULL,
    CTR_ID TINYINT UNSIGNED NOT NULL,

    FOREIGN KEY (CTR_ID) REFERENCES OCEAN_CONSTRUCTEUR(CTR_ID)
);

CREATE TABLE OCEAN_SITE (
    SIT_ID MEDIUMINT UNSIGNED NOT NULL PRIMARY KEY,
    DEP_NUM TINYINT UNSIGNED NOT NULL,
    REG_NUM TINYINT UNSIGNED NOT NULL,
    ZGE_ID SMALLINT UNSIGNED DEFAULT NULL,
    TPS_ID TINYINT UNSIGNED DEFAULT NULL,
    SIT_NUMG2R VARCHAR(10) DEFAULT NULL UNIQUE,
    SIT_NOM VARCHAR(50) NOT NULL,
    SIT_COOXREEL FLOAT(8,3) NOT NULL,
    SIT_COOYREEL FLOAT(8,3) NOT NULL,
    SIT_COOZREEL SMALLINT NOT NULL,
    SIT_COOXSIM FLOAT(8,3) NOT NULL,
    SIT_COOYSIM FLOAT(8,3) NOT NULL,
    SIT_COOZSIM SMALLINT NOT NULL,
    SIT_LONGIT VARCHAR(10) NOT NULL,
    SIT_LATIT VARCHAR(10) NOT NULL,
    SIT_NSCADAS VARCHAR(50) NOT NULL,
    SIT_NPCADAS VARCHAR(50) NOT NULL,
    SIT_INSEE VARCHAR(6) NOT NULL,
    SIT_COMMENT VARCHAR(250) NOT NULL,
    SIT_QUI VARCHAR(50) NOT NULL,
    SIT_QUAND DATETIME NOT NULL,
    SIT_ADRESSE VARCHAR(100) NOT NULL,
    SIT_COMPADR VARCHAR(50) NOT NULL,
    SIT_LIEUDIT VARCHAR(100) NOT NULL,
    SIT_CODPOST VARCHAR(5) NOT NULL,
    SIT_COMMUNE VARCHAR(50) NOT NULL,
    SIT_PROPR VARCHAR(15) NOT NULL,
    SIT_RESPONS VARCHAR(10) NOT NULL,
    SIT_TEL VARCHAR(10) NOT NULL,
    SIT_FAX VARCHAR(10) NOT NULL,
    SIT_VERSION SMALLINT NOT NULL,
    SIT_ZPID VARCHAR(15) DEFAULT NULL,
    TYPE_SITE_RS_ID TINYINT UNSIGNED DEFAULT NULL,
    SIT_PHASE TINYINT UNSIGNED DEFAULT NULL,
    OPP_ID TINYINT UNSIGNED NOT NULL,
    SIT_RS TINYINT UNSIGNED NOT NULL,
    SIT_ZONERS TINYINT UNSIGNED DEFAULT NULL,
    SIT_PLQEXPL VARCHAR(10) NOT NULL,
    SIT_SANTE BOOLEAN DEFAULT NULL,
    CONF_HARD VARCHAR(30) DEFAULT NULL,
    CONF_INTERNE VARCHAR(30) DEFAULT NULL,
    PLAQ_CONCEPT_ID VARCHAR(50) DEFAULT NULL,
    PLAQ_CONCEPT_LABEL VARCHAR(50) DEFAULT NULL,
    PLAQ_DEPL_LABEL VARCHAR(50) DEFAULT NULL,
    PLAQ_DEPL_ID VARCHAR(50) DEFAULT NULL,
    SPECIAUX_LABEL VARCHAR(30) DEFAULT NULL,
    FRONTIERE VARCHAR(1) DEFAULT NULL,
    SIT_ZONE VARCHAR(5) DEFAULT NULL,
    ERS_ID VARCHAR(30) DEFAULT NULL,

    FOREIGN KEY (DEP_NUM) REFERENCES OCEAN_REG_DEP(DEP_NUM),
    FOREIGN KEY (REG_NUM) REFERENCES OCEAN_REGION(REG_NUM),
    FOREIGN KEY (OPP_ID) REFERENCES OCEAN_OPERATORAPPLIC(OPP_ID)
);

CREATE TABLE OCEAN_SITE_INDEX (
    SIT_ID MEDIUMINT UNSIGNED NOT NULL PRIMARY KEY,
    ANT_INDEX SMALLINT UNSIGNED NOT NULL,
    BAI_INDEX SMALLINT UNSIGNED NOT NULL,
    REP_INDEX SMALLINT UNSIGNED NOT NULL,

    FOREIGN KEY (SIT_ID) REFERENCES OCEAN_SITE(SIT_ID)
);

CREATE TABLE OCEAN_OT (
    ODT_ID MEDIUMINT UNSIGNED NOT NULL PRIMARY KEY,
    SIT_ID MEDIUMINT UNSIGNED NOT NULL,
    ODT_NOM VARCHAR(30) NOT NULL,
    ODT_NUM MEDIUMINT UNSIGNED DEFAULT NULL,
    ODT_COMMENT VARCHAR(250) NOT NULL,
    ODT_QUI VARCHAR(50) NOT NULL,
    ODT_QUAND DATETIME NOT NULL,
    ODT_VERSION TINYINT UNSIGNED NOT NULL,

    FOREIGN KEY (SIT_ID) REFERENCES OCEAN_SITE(SIT_ID)
);

CREATE TABLE OCEAN_SOUSTYPE_RNCBSC (
    SOUSTYPE_ID SMALLINT UNSIGNED NOT NULL PRIMARY KEY,
    SOUSTYPE_LIB VARCHAR(50) NOT NULL,
    CTR_ID TINYINT UNSIGNED NOT NULL,
    TEC_ID TINYINT UNSIGNED NOT NULL,

    FOREIGN KEY (CTR_ID) REFERENCES OCEAN_CONSTRUCTEUR(CTR_ID),
    FOREIGN KEY (TEC_ID) REFERENCES OCEAN_TECHNO(TEC_ID)
);

CREATE TABLE OCEAN_TILTEL (
    TLT_ID SMALLINT UNSIGNED NOT NULL PRIMARY KEY,
    CTA_ID SMALLINT UNSIGNED NOT NULL,
    TLT_LIB TINYINT NOT NULL,
    TLT_DEF BOOLEAN NOT NULL,
    BAN_ID SMALLINT UNSIGNED NOT NULL,

    FOREIGN KEY (BAN_ID) REFERENCES OCEAN_BANDE(BAN_ID),
    FOREIGN KEY (CTA_ID) REFERENCES OCEAN_CATALANT(CTA_ID)
);

CREATE TABLE OCEAN_ANTENNE (
    ANT_ID INT UNSIGNED NOT NULL PRIMARY KEY,
    ANT_SOURCEID INT UNSIGNED DEFAULT NULL,
    CTA_ID SMALLINT UNSIGNED NOT NULL,
    SIT_ID MEDIUMINT UNSIGNED NOT NULL,
    ANT_NUM SMALLINT UNSIGNED NOT NULL,
    ANT_INDEX SMALLINT UNSIGNED NOT NULL,
    ANT_NUMSECT TINYINT UNSIGNED NOT NULL,
    ANT_AZIMUT SMALLINT NOT NULL,
    ANT_HBASE FLOAT(8,3) NOT NULL,
    ANT_HBSIM FLOAT(8,3) NOT NULL,
    ANT_TILTMQ SMALLINT NOT NULL,
    ANT_COOXREEL FLOAT(8,3) NOT NULL,
    ANT_COOYREEL FLOAT(8,3) NOT NULL,
    ANT_COOZREEL SMALLINT NOT NULL,
    ANT_COOXSIMUL FLOAT(8,3) NOT NULL,
    ANT_COOYSIMUL FLOAT(8,3) NOT NULL,
    ANT_COOZSIMUL SMALLINT NOT NULL,
    ANT_NONINST TINYINT UNSIGNED NOT NULL,
    ANT_COMMENT VARCHAR(250) NOT NULL,
    ANT_QUI VARCHAR(50) NOT NULL,
    ANT_QUAND DATETIME NOT NULL,
    ANT_VERSION SMALLINT NOT NULL,
    ANT_ZPID VARCHAR(100) NOT NULL,
    ANT_SANTE TINYINT DEFAULT NULL,
    ANT_RANG TINYINT DEFAULT NULL,

    FOREIGN KEY (CTA_ID) REFERENCES OCEAN_CATALANT(CTA_ID),
    FOREIGN KEY (SIT_ID) REFERENCES OCEAN_SITE(SIT_ID)
);

CREATE TABLE OCEAN_REPETEUR (
    REP_ID SMALLINT UNSIGNED NOT NULL PRIMARY KEY,
    REP_SOURCEID SMALLINT UNSIGNED DEFAULT NULL,
    SIT_ID MEDIUMINT UNSIGNED NOT NULL,
    CRE_ID SMALLINT UNSIGNED NOT NULL,
    REP_NUM MEDIUMINT UNSIGNED NOT NULL,
    REP_INDEX TINYINT UNSIGNED NOT NULL,
    REP_MEMO VARCHAR(40) DEFAULT NULL,
    REP_COOX FLOAT(8,3) NOT NULL,
    REP_COOY FLOAT(8,3) NOT NULL,
    REP_COOZ SMALLINT NOT NULL,
    REP_SUPER BOOLEAN NOT NULL,
    REP_MODEM VARCHAR(15) DEFAULT NULL,
    REP_MASTER VARCHAR(35) DEFAULT NULL,
    REP_NONINST TINYINT UNSIGNED NOT NULL,
    REP_COMMENT VARCHAR(250) NOT NULL,
    REP_QUI VARCHAR(50) NOT NULL,
    REP_QUAND DATETIME NOT NULL,
    REP_VERSION TINYINT NOT NULL,

    FOREIGN KEY (REP_SOURCEID) REFERENCES OCEAN_REPETEUR(REP_ID),
    FOREIGN KEY (SIT_ID) REFERENCES OCEAN_SITE(SIT_ID),
    FOREIGN KEY (CRE_ID) REFERENCES OCEAN_CATALREP(CRE_ID)
);

CREATE TABLE OCEAN_MODELE (
    MOD_ID MEDIUMINT UNSIGNED NOT NULL PRIMARY KEY,
    PPA_ID TINYINT UNSIGNED NOT NULL,
    PAL_ID SMALLINT UNSIGNED NOT NULL,
    REG_NUM TINYINT UNSIGNED NOT NULL,
    MOD_LIB VARCHAR(50) NOT NULL,
    MOD_IDOMC SMALLINT UNSIGNED DEFAULT NULL,
    MOD_FLGDEF BOOLEAN NOT NULL,
    MOD_QUI VARCHAR(50) NOT NULL,
    MOD_QUAND DATETIME NOT NULL,
    MOD_VERSION TINYINT UNSIGNED NOT NULL,
    MOD_EXTRA MEDIUMINT UNSIGNED DEFAULT NULL,

    FOREIGN KEY (PPA_ID) REFERENCES OCEAN_PORTEEPARAM(PPA_ID),
    FOREIGN KEY (PAL_ID) REFERENCES OCEAN_PALIER(PAL_ID),
    FOREIGN KEY (REG_NUM) REFERENCES OCEAN_REGION(REG_NUM)
);

CREATE TABLE OCEAN_JEUPARAM (
    JPA_ID INT NOT NULL PRIMARY KEY,
    PPA_ID TINYINT UNSIGNED NOT NULL,
    JPA_IDOBJ INT NOT NULL,
    JPA_NUMDI INT DEFAULT NULL,
    MOD_ID MEDIUMINT UNSIGNED NOT NULL,
    ESW_ID TINYINT UNSIGNED NOT NULL,
    JPA_QUI VARCHAR(50) NOT NULL,
    JPA_QUAND DATETIME NOT NULL,
    JPA_VERSION SMALLINT NOT NULL,

    FOREIGN KEY (PPA_ID) REFERENCES OCEAN_PORTEEPARAM(PPA_ID),
    FOREIGN KEY (MOD_ID) REFERENCES OCEAN_MODELE(MOD_ID),
    FOREIGN KEY (ESW_ID) REFERENCES OCEAN_ETATSW(ESW_ID)
);

CREATE TABLE OCEAN_PARAMETRE (
    PAR_ID MEDIUMINT UNSIGNED NOT NULL PRIMARY KEY,
    PAL_ID SMALLINT UNSIGNED NOT NULL,
    TPA_ID TINYINT UNSIGNED NOT NULL,
    GPR_ID SMALLINT UNSIGNED NOT NULL,
    PNA_ID SMALLINT UNSIGNED DEFAULT NULL,
    PPA_ID TINYINT UNSIGNED NOT NULL,
    POP_ID TINYINT UNSIGNED DEFAULT NULL,
    PAR_LIB VARCHAR(100) NOT NULL,
    PAR_LONG TINYINT UNSIGNED DEFAULT NULL,
    PAR_VALDEF VARCHAR(50) NOT NULL,
    PAR_MIN VARCHAR(20) DEFAULT NULL,
    PAR_MAX VARCHAR(20) DEFAULT NULL,
    PAR_PAS VARCHAR(20) DEFAULT NULL,
    PAR_UNITE VARCHAR(20) DEFAULT NULL,
    PAR_QUI VARCHAR(50) NOT NULL,
    PAR_QUAND DATETIME NOT NULL,
    PAR_VERSION SMALLINT UNSIGNED NOT NULL,
    PAR_EXTRA VARCHAR(5) DEFAULT NULL,
    CCLB BOOLEAN NOT NULL,
    PAR_LIB_OMC VARCHAR(100) DEFAULT NULL,

    FOREIGN KEY (PAL_ID) REFERENCES OCEAN_PALIER(PAL_ID),
    FOREIGN KEY (GPR_ID) REFERENCES OCEAN_GRPPARAM(GPR_ID),
    FOREIGN KEY (PPA_ID) REFERENCES OCEAN_PORTEEPARAM(PPA_ID)
);

CREATE TABLE OCEAN_SOUSMODELE (
    SMO_ID MEDIUMINT UNSIGNED NOT NULL PRIMARY KEY,
    MOD_ID MEDIUMINT UNSIGNED NOT NULL,
    SMO_RANG TINYINT UNSIGNED NOT NULL,
    SMO_QUI VARCHAR(50) NOT NULL,
    SMO_QUAND DATETIME NOT NULL,
    SMO_VERSION TINYINT UNSIGNED NOT NULL,

    FOREIGN KEY (MOD_ID) REFERENCES OCEAN_MODELE(MOD_ID)
);

CREATE TABLE OCEAN_PARAMSTDMOD (
    PSM_ID INT UNSIGNED NOT NULL PRIMARY KEY,
    MOD_ID MEDIUMINT UNSIGNED NOT NULL,
    PAR_ID MEDIUMINT UNSIGNED NOT NULL,
    PSM_VALSTD VARCHAR(50) NOT NULL,
    PSM_NUMDI VARCHAR(6) DEFAULT NULL,
    PSM_FLGPRINC BOOLEAN NOT NULL,

    FOREIGN KEY (MOD_ID) REFERENCES OCEAN_MODELE(MOD_ID),
    FOREIGN KEY (PAR_ID) REFERENCES OCEAN_PARAMETRE(PAR_ID)
);

CREATE TABLE OCEAN_JEUPARSSMOD (
    JSS_ID MEDIUMINT UNSIGNED NOT NULL PRIMARY KEY,
    SMO_ID MEDIUMINT UNSIGNED NOT NULL,
    JSS_RANG TINYINT UNSIGNED NOT NULL,

    FOREIGN KEY (SMO_ID) REFERENCES OCEAN_SOUSMODELE(SMO_ID)
);

CREATE TABLE OCEAN_INTSSMODELE (
    ISS_ID MEDIUMINT UNSIGNED NOT NULL PRIMARY KEY,
    INT_ID SMALLINT UNSIGNED NOT NULL,
    JSS_ID MEDIUMINT UNSIGNED NOT NULL,
    ISS_NUMINT TINYINT UNSIGNED NOT NULL,
    ISS_NUMDI TINYINT UNSIGNED DEFAULT NULL,

    FOREIGN KEY (JSS_ID) REFERENCES OCEAN_JEUPARSSMOD(JSS_ID)
);

CREATE TABLE OCEAN_BAIE (
    BAI_ID MEDIUMINT UNSIGNED NOT NULL PRIMARY KEY,
    BAI_SOURCEID MEDIUMINT UNSIGNED DEFAULT NULL,
    SIT_ID MEDIUMINT UNSIGNED NOT NULL,
    CTB_ID SMALLINT UNSIGNED NOT NULL,
    COM_ID SMALLINT UNSIGNED NOT NULL,
    REL_ID TINYINT UNSIGNED DEFAULT NULL,
    NAT_ID SMALLINT UNSIGNED NOT NULL,
    BAI_NUM TINYINT UNSIGNED NOT NULL,
    BAI_INDEX TINYINT UNSIGNED NOT NULL,
    BAI_NONINST TINYINT UNSIGNED NOT NULL,
    BAI_FLGOK TINYINT UNSIGNED NOT NULL,
    BAI_NBEXTEN TINYINT UNSIGNED NOT NULL,
    BAI_COMMENT VARCHAR(250) NOT NULL,
    BAI_QUI VARCHAR(50) NOT NULL,
    BAI_QUAND DATETIME NOT NULL,
    BAI_VERSION SMALLINT NOT NULL,
    RSL_ID TINYINT UNSIGNED DEFAULT NULL,
    BAI_NE_2G VARCHAR(15) DEFAULT NULL,
    BAI_NE_3G VARCHAR(15) DEFAULT NULL,
    BBU2G_ID SMALLINT UNSIGNED DEFAULT NULL,
    BBU3G_ID SMALLINT UNSIGNED DEFAULT NULL,
    ENODEB_ID VARCHAR(10) DEFAULT NULL,
    BAI_NE_4G VARCHAR(15) DEFAULT NULL,
    BBU4G_ID SMALLINT UNSIGNED DEFAULT NULL,
    CFG_ID VARCHAR(30) DEFAULT NULL,

    FOREIGN KEY (BAI_SOURCEID) REFERENCES OCEAN_BAIE(BAI_ID),
    FOREIGN KEY (SIT_ID) REFERENCES OCEAN_SITE(SIT_ID),
    FOREIGN KEY (CTB_ID) REFERENCES OCEAN_CATALBAIE(CTB_ID),
    FOREIGN KEY (COM_ID) REFERENCES OCEAN_COMBINER(COM_ID),
    FOREIGN KEY (NAT_ID) REFERENCES OCEAN_NATURE(NAT_ID),
    FOREIGN KEY (BBU2G_ID) REFERENCES OCEAN_MODBBU(BBU_ID),
    FOREIGN KEY (BBU3G_ID) REFERENCES OCEAN_MODBBU(BBU_ID),
    FOREIGN KEY (BBU4G_ID) REFERENCES OCEAN_MODBBU(BBU_ID)
);

CREATE TABLE OCEAN_DEMANDIMPEXP (
    DIE_ID MEDIUMINT UNSIGNED NOT NULL PRIMARY KEY,
    CIE_ID SMALLINT UNSIGNED NOT NULL,
    EIE_ID TINYINT UNSIGNED NOT NULL,
    UTI_ID SMALLINT UNSIGNED NOT NULL,
    DIE_NOM VARCHAR(30) NOT NULL,
    DIE_COMMENTAIRE VARCHAR(250) NOT NULL,
    DIE_DATE_CREATION DATETIME NOT NULL,
    DIE_DATE_LANCEMENT DATETIME NOT NULL,
    DIE_FICENTREE VARCHAR(100) NOT NULL,
    DIE_FICSORTIE VARCHAR(100) NOT NULL,
    DIE_CR VARCHAR(255) NOT NULL,
    DIE_QUI VARCHAR(50) NOT NULL,
    DIE_QUAND DATETIME NOT NULL,
    DIE_TYPE_LANCEMENT TINYINT NOT NULL,
    DIE_TYPE_TRAITEMENT TINYINT NOT NULL,

    FOREIGN KEY (CIE_ID) REFERENCES OCEAN_CATALIMPEXP(CIE_ID),
    FOREIGN KEY (EIE_ID) REFERENCES OCEAN_ETATIE(EIE_ID)
);

CREATE TABLE OCEAN_DEMANDMODI (
    DDM_ID INT UNSIGNED NOT NULL PRIMARY KEY,
    REG_NUM TINYINT UNSIGNED NOT NULL,
    TDM_ID TINYINT UNSIGNED NOT NULL,
    ODT_NUM MEDIUMINT UNSIGNED DEFAULT NULL,
    EDM_ID TINYINT UNSIGNED NOT NULL,
    DDM_COMMENT VARCHAR(250) NOT NULL,
    DDM_COMREJET VARCHAR(70) NOT NULL,
    DDM_IDELEM INT UNSIGNED DEFAULT NULL,
    DDM_TYPELEM TINYINT UNSIGNED NOT NULL,
    DDM_DATPREV DATETIME DEFAULT NULL,
    DDM_AUTGEN VARCHAR(50) NOT NULL,
    DDM_DATGEN DATETIME NOT NULL,
    DDM_QUI VARCHAR(50) NOT NULL,
    DDM_QUAND DATETIME NOT NULL,
    DDM_VERSION SMALLINT UNSIGNED NOT NULL,
    CHP_ID MEDIUMINT UNSIGNED DEFAULT NULL,

    FOREIGN KEY (REG_NUM) REFERENCES OCEAN_REGION(REG_NUM),
    FOREIGN KEY (TDM_ID) REFERENCES OCEAN_TYPEDEMANDE(TDM_ID),
    FOREIGN KEY (EDM_ID) REFERENCES OCEAN_ETATDM(EDM_ID)
);

CREATE TABLE OCEAN_MODEREP (
    MDR_ID SMALLINT UNSIGNED NOT NULL PRIMARY KEY,
    MDR_SOURCEID SMALLINT UNSIGNED DEFAULT NULL,
    REP_ID SMALLINT UNSIGNED NOT NULL,
    SYS_ID TINYINT UNSIGNED NOT NULL,
    MDR_POWER TINYINT DEFAULT NULL,
    MDR_ATTUP TINYINT UNSIGNED DEFAULT NULL,
    MDR_ATTDOWN TINYINT UNSIGNED DEFAULT NULL,
    MDR_GAIN FLOAT(5,2) DEFAULT NULL,
    MDR_NONINST TINYINT UNSIGNED NOT NULL,
    MDR_COMMENT VARCHAR(250) NOT NULL,
    MDR_QUI VARCHAR(50) NOT NULL,
    MDR_QUAND DATETIME NOT NULL,
    MDR_VERSION TINYINT NOT NULL,

    FOREIGN KEY (MDR_SOURCEID) REFERENCES OCEAN_MODEREP(MDR_ID),
    FOREIGN KEY (REP_ID) REFERENCES OCEAN_REPETEUR(REP_ID),
    FOREIGN KEY (SYS_ID) REFERENCES OCEAN_SYSTEME(SYS_ID)
);

CREATE TABLE OCEAN_ODT_ANT (
    OTA_ID MEDIUMINT UNSIGNED NOT NULL PRIMARY KEY,
    ODT_ID MEDIUMINT UNSIGNED NOT NULL,
    ANT_ID INT UNSIGNED NOT NULL,
    OTA_FLAG TINYINT UNSIGNED NOT NULL,

    FOREIGN KEY (ODT_ID) REFERENCES OCEAN_OT(ODT_ID),
    FOREIGN KEY (ANT_ID) REFERENCES OCEAN_ANTENNE(ANT_ID)
);

CREATE TABLE OCEAN_ODT_BAI (
    OTB_ID MEDIUMINT UNSIGNED NOT NULL PRIMARY KEY,
    BAI_ID MEDIUMINT UNSIGNED NOT NULL,
    ODT_ID MEDIUMINT UNSIGNED NOT NULL,
    OTB_FLAG TINYINT UNSIGNED NOT NULL,

    FOREIGN KEY (BAI_ID) REFERENCES OCEAN_BAIE(BAI_ID),
    FOREIGN KEY (ODT_ID) REFERENCES OCEAN_OT(ODT_ID)
);

CREATE TABLE OCEAN_RNCBSC (
    RBC_ID INT UNSIGNED NOT NULL PRIMARY KEY,
    TEC_ID TINYINT UNSIGNED NOT NULL,
    REG_NUM TINYINT UNSIGNED NOT NULL,
    CTR_ID TINYINT UNSIGNED NOT NULL,
    RBC_IDMET INT UNSIGNED DEFAULT NULL,
    RBC_NOM VARCHAR(30) NOT NULL,
    RBC_SITE MEDIUMINT UNSIGNED NOT NULL,
    RBC_PTSEM MEDIUMINT UNSIGNED DEFAULT NULL,
    RBC_COMMENT VARCHAR(250) NOT NULL,
    RBC_QUI VARCHAR(50) NOT NULL,
    RBC_QUAND DATETIME NOT NULL,
    RBC_VERSION TINYINT UNSIGNED NOT NULL,
    SOUSTYPE SMALLINT UNSIGNED DEFAULT NULL,

    FOREIGN KEY (TEC_ID) REFERENCES OCEAN_TECHNO(TEC_ID),
    FOREIGN KEY (REG_NUM) REFERENCES OCEAN_REGION(REG_NUM),
    FOREIGN KEY (CTR_ID) REFERENCES OCEAN_CONSTRUCTEUR(CTR_ID),
    FOREIGN KEY (RBC_IDMET) REFERENCES OCEAN_RNCBSC(RBC_ID),
    FOREIGN KEY (SOUSTYPE) REFERENCES OCEAN_SOUSTYPE_RNCBSC(SOUSTYPE_ID)
);

CREATE TABLE OCEAN_RBC_LAC (
    LAC_ID SMALLINT UNSIGNED NOT NULL PRIMARY KEY,
    LAC_VALUE SMALLINT UNSIGNED NOT NULL,
    OPP_ID TINYINT UNSIGNED NOT NULL,
    RBC_ID INT UNSIGNED NOT NULL,
    TYPEPROJET_ID VARCHAR(8) DEFAULT NULL,

    FOREIGN KEY (OPP_ID) REFERENCES OCEAN_OPERATORAPPLIC(OPP_ID),
    FOREIGN KEY (RBC_ID) REFERENCES OCEAN_RNCBSC(RBC_ID)
);

CREATE TABLE OCEAN_RBC_RAC (
    RAC_ID SMALLINT UNSIGNED NOT NULL PRIMARY KEY,
    RAC_VALUE TINYINT UNSIGNED NOT NULL,
    RBC_ID INT UNSIGNED NOT NULL,

    FOREIGN KEY (RBC_ID) REFERENCES OCEAN_RNCBSC(RBC_ID)
);

CREATE TABLE OCEAN_PARAMSPEC (
    PSC_ID INT UNSIGNED NOT NULL PRIMARY KEY,
    JPA_ID INT NOT NULL,
    PAR_ID MEDIUMINT UNSIGNED NOT NULL,
    JUS_ID TINYINT UNSIGNED NOT NULL,
    PSC_VALSPEC VARCHAR(50) NOT NULL,
    PSC_NUMDI VARCHAR(6) DEFAULT NULL,
    PSC_QUI VARCHAR(50) NOT NULL,
    PSC_QUAND DATETIME NOT NULL,
    PSC_VERSION SMALLINT UNSIGNED NOT NULL,
    PSC_COMMENT VARCHAR(250) NOT NULL,

    FOREIGN KEY (JPA_ID) REFERENCES OCEAN_JEUPARAM(JPA_ID),
    FOREIGN KEY (PAR_ID) REFERENCES OCEAN_PARAMETRE(PAR_ID)
);

CREATE TABLE OCEAN_PARAMSTDSSMOD (
    PSS_ID INT UNSIGNED NOT NULL PRIMARY KEY,
    PAR_ID MEDIUMINT UNSIGNED NOT NULL,
    JSS_ID MEDIUMINT UNSIGNED NOT NULL,
    PSS_VALSTD VARCHAR(11) NOT NULL,
    PSS_NUMDI VARCHAR(6) DEFAULT NULL,

    FOREIGN KEY (PAR_ID) REFERENCES OCEAN_PARAMETRE(PAR_ID),
    FOREIGN KEY (JSS_ID) REFERENCES OCEAN_JEUPARSSMOD(JSS_ID)
);

CREATE TABLE OCEAN_RBC_BAIE (
    RBB_ID MEDIUMINT UNSIGNED NOT NULL PRIMARY KEY,
    BAI_ID MEDIUMINT UNSIGNED NOT NULL,
    RBB_QUAND DATETIME NOT NULL,
    RBB_ETAT TINYINT UNSIGNED NOT NULL,
    TEC_ID TINYINT UNSIGNED NOT NULL,
    RBC_ID INT UNSIGNED NOT NULL,
    RBB_QUI VARCHAR(50) NOT NULL,

    FOREIGN KEY (BAI_ID) REFERENCES OCEAN_BAIE(BAI_ID),
    FOREIGN KEY (TEC_ID) REFERENCES OCEAN_TECHNO(TEC_ID),
    FOREIGN KEY (RBC_ID) REFERENCES OCEAN_RNCBSC(RBC_ID)
);

CREATE TABLE OCEAN_ODT_RBC (
    OTR_ID MEDIUMINT UNSIGNED NOT NULL PRIMARY KEY,
    RBB_ID MEDIUMINT UNSIGNED NOT NULL,
    ODT_ID MEDIUMINT UNSIGNED NOT NULL,
    OTR_FLAG TINYINT UNSIGNED NOT NULL,

    FOREIGN KEY (RBB_ID) REFERENCES OCEAN_RBC_BAIE(RBB_ID),
    FOREIGN KEY (ODT_ID) REFERENCES OCEAN_OT(ODT_ID)
);

CREATE TABLE OCEAN_LAC_BAIE (
    LAC_BAIE_ID MEDIUMINT UNSIGNED NOT NULL PRIMARY KEY,
    LAC_ID SMALLINT UNSIGNED NOT NULL,
    RBB_ID MEDIUMINT UNSIGNED NOT NULL,
    LAC_BAIE_QUAND DATETIME NOT NULL,

    FOREIGN KEY (LAC_ID) REFERENCES OCEAN_RBC_LAC(LAC_ID),
    FOREIGN KEY (RBB_ID) REFERENCES OCEAN_RBC_BAIE(RBB_ID)
);

CREATE TABLE OCEAN_RAC_BAIE (
    RAC_BAIE_ID MEDIUMINT UNSIGNED NOT NULL PRIMARY KEY,
    RAC_ID SMALLINT UNSIGNED NOT NULL,
    RBB_ID MEDIUMINT UNSIGNED NOT NULL,
    RAC_BAIE_QUAND DATETIME NOT NULL,

    FOREIGN KEY (RAC_ID) REFERENCES OCEAN_RBC_RAC(RAC_ID),
    FOREIGN KEY (RBB_ID) REFERENCES OCEAN_RBC_BAIE(RBB_ID)
);

CREATE TABLE OCEAN_CELLULE (
    CELL_ID INT UNSIGNED NOT NULL PRIMARY KEY,
    RBC_ID INT UNSIGNED NOT NULL,
    SYS_ID TINYINT UNSIGNED NOT NULL,
    ENV_ID TINYINT UNSIGNED NOT NULL,
    TPC_ID TINYINT UNSIGNED NOT NULL,
    ZSE_ID MEDIUMINT UNSIGNED NOT NULL,
    ZVI_ID MEDIUMINT UNSIGNED NOT NULL,
    ZRE_ID TINYINT UNSIGNED NOT NULL,
    ZSP_ID TINYINT UNSIGNED NOT NULL,
    ZFR_ID TINYINT UNSIGNED NOT NULL,
    ZDE_ID TINYINT UNSIGNED NOT NULL,
    CELL_NUMSECT TINYINT UNSIGNED NOT NULL,
    CELL_OBJMARK VARCHAR(10) DEFAULT NULL,
    CELL_COMF2G VARCHAR(100) NOT NULL,
    CELL_NUMDI MEDIUMINT UNSIGNED DEFAULT NULL,
    F3G_ID TINYINT UNSIGNED DEFAULT NULL,
    CELL_NUM SMALLINT UNSIGNED NOT NULL,
    CELL_CI MEDIUMINT UNSIGNED DEFAULT NULL,
    CELL_LAC SMALLINT UNSIGNED DEFAULT NULL,
    CELL_RAC TINYINT UNSIGNED DEFAULT NULL,
    CELL_SAC MEDIUMINT UNSIGNED DEFAULT NULL,
    CELL_FSERV BOOLEAN NOT NULL,
    CELL_TCELL TINYINT UNSIGNED DEFAULT NULL,
    CELL_AUTINT VARCHAR(50) DEFAULT NULL,
    CELL_DATINT DATETIME DEFAULT NULL,
    CELL_PEM FLOAT(3, 1) DEFAULT NULL,
    CELL_DATMES DATETIME DEFAULT NULL,
    CELL_DATMESPREV VARCHAR(20) DEFAULT NULL,
    CELL_AUTCHGSTAT VARCHAR(50) DEFAULT NULL,
    CELL_DATCHGSTAT DATETIME DEFAULT NULL,
    CELL_SCODE SMALLINT UNSIGNED DEFAULT NULL,
    CELL_PLAN VARCHAR(10) DEFAULT NULL,
    CELL_SSPLAN VARCHAR(10) DEFAULT NULL,
    CELL_COMMENT VARCHAR(250) NOT NULL,
    CELL_QUI VARCHAR(50) NOT NULL,
    CELL_QUAND DATETIME NOT NULL,
    CELL_VERSION TINYINT NOT NULL,
    CTR_ID TINYINT UNSIGNED NOT NULL,
    ESW_ID TINYINT UNSIGNED NOT NULL,
    SIT_ID MEDIUMINT UNSIGNED NOT NULL,
    PLMNVT TINYINT UNSIGNED DEFAULT NULL,
    ZONE_ID TINYINT UNSIGNED DEFAULT NULL,
    OPP_ID TINYINT UNSIGNED NOT NULL,
    CELL_ZPID VARCHAR(15) DEFAULT NULL,
    ENODEB_ID VARCHAR(10) DEFAULT NULL,
    CELL_ECI INT UNSIGNED DEFAULT NULL,
    TPCL_ID TINYINT UNSIGNED DEFAULT NULL,
    CELL_TAC MEDIUMINT UNSIGNED DEFAULT NULL,
    CELL_PCI SMALLINT UNSIGNED DEFAULT NULL,
    F4G_ID TINYINT UNSIGNED DEFAULT NULL,
    ANR TINYINT UNSIGNED NOT NULL,
    CCLB TINYINT UNSIGNED NOT NULL,
    SERVICE_SUSPENDU TINYINT UNSIGNED NOT NULL,
    ID_RSCELL TINYINT UNSIGNED DEFAULT NULL,
    ID_MAXPOWER TINYINT UNSIGNED DEFAULT NULL,
    ID_BANDWIDTH TINYINT UNSIGNED DEFAULT NULL,
    CELL_MOCN TINYINT UNSIGNED DEFAULT NULL,
    CELL_MNC TINYINT UNSIGNED NOT NULL,
    CELL_MCC TINYINT UNSIGNED NOT NULL,
    CCLB_SUSPENDU TINYINT UNSIGNED NOT NULL,
    CELL_NAME VARCHAR(25) NOT NULL,
    CELL_MONACO VARCHAR(1) DEFAULT NULL,
    FREQ_ROLE TINYINT UNSIGNED DEFAULT NULL,

    FOREIGN KEY (RBC_ID) REFERENCES OCEAN_RNCBSC(RBC_ID),
    FOREIGN KEY (SYS_ID) REFERENCES OCEAN_SYSTEME(SYS_ID),
    FOREIGN KEY (ENV_ID) REFERENCES OCEAN_ENVIRONMNT(ENV_ID),
    FOREIGN KEY (TPC_ID) REFERENCES OCEAN_TYPCELL(TPC_ID),
    FOREIGN KEY (ZSE_ID) REFERENCES OCEAN_ZONESERVICE(ZSE_ID),
    FOREIGN KEY (ZVI_ID) REFERENCES OCEAN_ZONEVIE(ZVI_ID),
    FOREIGN KEY (ZRE_ID) REFERENCES OCEAN_ZONERESEAUX(ZRE_ID),
    FOREIGN KEY (ZSP_ID) REFERENCES OCEAN_ZONESPEC(ZSP_ID),
    FOREIGN KEY (F3G_ID) REFERENCES OCEAN_FREQUENCE3G(F3G_ID),
    FOREIGN KEY (CTR_ID) REFERENCES OCEAN_CONSTRUCTEUR(CTR_ID),
    FOREIGN KEY (ESW_ID) REFERENCES OCEAN_ETATSW(ESW_ID),
    FOREIGN KEY (SIT_ID) REFERENCES OCEAN_SITE(SIT_ID),
    FOREIGN KEY (OPP_ID) REFERENCES OCEAN_OPERATORAPPLIC(OPP_ID),
    FOREIGN KEY (F4G_ID) REFERENCES OCEAN_FREQUENCE4G(F4G_ID)
);

CREATE TABLE OCEAN_VOISINAGE (
    VOG_ID INT UNSIGNED NOT NULL PRIMARY KEY,
    CELL_IDCIBLE INT UNSIGNED NOT NULL,
    CELL_IDSOURCE INT UNSIGNED NOT NULL,
    ESW_ID TINYINT UNSIGNED NOT NULL,
    VOG_COMMENT VARCHAR(250) NOT NULL,
    VOG_FLGSUP BOOLEAN NOT NULL,
    VOG_NUMDI MEDIUMINT UNSIGNED DEFAULT NULL,
    VOG_QUI VARCHAR(50) NOT NULL,
    VOG_QUAND DATETIME NOT NULL,
    VOG_VERSION TINYINT UNSIGNED NOT NULL,
    MODE_ID TINYINT UNSIGNED NOT NULL,
    FANR BOOLEAN NOT NULL,

    FOREIGN KEY (CELL_IDCIBLE) REFERENCES OCEAN_CELLULE(CELL_ID),
    FOREIGN KEY (CELL_IDSOURCE) REFERENCES OCEAN_CELLULE(CELL_ID),
    FOREIGN KEY (ESW_ID) REFERENCES OCEAN_ETATSW(ESW_ID)
);

CREATE TABLE OCEAN_CDM_CELL (
    ACD_ID MEDIUMINT UNSIGNED NOT NULL PRIMARY KEY,
    CDM_ID TINYINT UNSIGNED NOT NULL,
    CELL_ID INT UNSIGNED NOT NULL,
    ACD_NOUVVAL FLOAT(5,1) NOT NULL,
    ACD_VERSION TINYINT NOT NULL,
    ACD_QUI VARCHAR(50) NOT NULL,
    ACD_QUAND DATETIME NOT NULL,

    FOREIGN KEY (CDM_ID) REFERENCES OCEAN_ATTCELLDM(CDM_ID),
    FOREIGN KEY (CELL_ID) REFERENCES OCEAN_CELLULE(CELL_ID)
);

CREATE TABLE OCEAN_CELLULE_ATT (
    CATT_ID MEDIUMINT UNSIGNED NOT NULL PRIMARY KEY,
    CELL_ID INT UNSIGNED NOT NULL,
    ATT_ID TINYINT UNSIGNED NOT NULL,
    ATT_VALUE VARCHAR(20) DEFAULT NULL,

    FOREIGN KEY (CELL_ID) REFERENCES OCEAN_CELLULE(CELL_ID),
    FOREIGN KEY (ATT_ID) REFERENCES OCEAN_REF_CELL_ATTRIBUT(ATT_ID)
);

CREATE TABLE OCEAN_CELL_VOIS_OPTIERS (
    CELL_ID INT UNSIGNED NOT NULL PRIMARY KEY,
    MCC TINYINT UNSIGNED NOT NULL,
    MNC TINYINT UNSIGNED NOT NULL,
    NCC TINYINT UNSIGNED DEFAULT NULL,
    BCC TINYINT UNSIGNED DEFAULT NULL,
    BCCH SMALLINT UNSIGNED DEFAULT NULL,
    CIO TINYINT UNSIGNED DEFAULT NULL,
    CELL_TX VARCHAR(5) DEFAULT NULL,
    RBC_ID INT UNSIGNED DEFAULT NULL,
    SYS_ID TINYINT UNSIGNED NOT NULL,
    ENV_ID TINYINT UNSIGNED DEFAULT NULL,
    TPC_ID TINYINT UNSIGNED NOT NULL,
    ZSE_ID MEDIUMINT UNSIGNED DEFAULT NULL,
    ZVI_ID MEDIUMINT UNSIGNED DEFAULT NULL,
    ZRE_ID TINYINT UNSIGNED DEFAULT NULL,
    ZSP_ID TINYINT UNSIGNED DEFAULT NULL,
    ZFR_ID TINYINT UNSIGNED DEFAULT NULL,
    ZDE_ID TINYINT UNSIGNED DEFAULT NULL,
    CELL_NUMSECT TINYINT UNSIGNED NOT NULL,
    CELL_OBJMARK TINYINT UNSIGNED DEFAULT NULL,
    CELL_COMF2G TINYINT UNSIGNED DEFAULT NULL,
    CELL_NUMDI TINYINT UNSIGNED DEFAULT NULL,
    F3G_FREQ SMALLINT UNSIGNED DEFAULT NULL,
    CELL_NUM TINYINT UNSIGNED DEFAULT NULL,
    CELL_CI SMALLINT UNSIGNED NOT NULL,
    CELL_LAC SMALLINT UNSIGNED NOT NULL,
    CELL_RAC TINYINT UNSIGNED DEFAULT NULL,
    CELL_SAC SMALLINT UNSIGNED DEFAULT NULL,
    CELL_FSERV TINYINT UNSIGNED NOT NULL,
    CELL_TCELL TINYINT UNSIGNED DEFAULT NULL,
    CELL_AUTINT TINYINT UNSIGNED DEFAULT NULL,
    CELL_DATINT DATETIME DEFAULT NULL,
    CELL_PEM TINYINT UNSIGNED DEFAULT NULL,
    CELL_DATMES DATETIME DEFAULT NULL,
    CELL_DATMESPREV DATETIME DEFAULT NULL,
    CELL_AUTCHGSTAT TINYINT UNSIGNED DEFAULT NULL,
    CELL_DATCHGSTAT DATETIME DEFAULT NULL,
    CELL_SCODE SMALLINT UNSIGNED DEFAULT NULL,
    CELL_PLAN TINYINT UNSIGNED DEFAULT NULL,
    CELL_SSPLAN TINYINT UNSIGNED DEFAULT NULL,
    CELL_COMMENT VARCHAR(15) NOT NULL,
    CELL_QUI VARCHAR(50) NOT NULL,
    CELL_QUAND DATETIME NOT NULL,
    CELL_VERSION TINYINT UNSIGNED NOT NULL,
    CTR_ID TINYINT UNSIGNED NOT NULL,
    ESW_ID TINYINT UNSIGNED NOT NULL,
    SIT_ID MEDIUMINT UNSIGNED NOT NULL,
    PLMNVT TINYINT UNSIGNED DEFAULT NULL,
    ZONE_ID TINYINT UNSIGNED NOT NULL,
    CELL_ZPID VARCHAR(15) DEFAULT NULL,
    OPP_ID TINYINT UNSIGNED NOT NULL,
    GAB_ID SMALLINT UNSIGNED NOT NULL,
    RBC_ID2 INT UNSIGNED DEFAULT NULL,
    UARFCN_UL SMALLINT UNSIGNED DEFAULT NULL,
    ENODEB_ID VARCHAR(10) DEFAULT NULL,
    CELL_PCI SMALLINT UNSIGNED DEFAULT NULL,
    CELL_TAC SMALLINT UNSIGNED DEFAULT NULL,
    MSRXLEVMIN TINYINT DEFAULT NULL,
    F4G_FREQ SMALLINT UNSIGNED DEFAULT NULL,
    CELL_MNC TINYINT UNSIGNED NOT NULL,
    CELL_MCC TINYINT UNSIGNED NOT NULL,

    FOREIGN KEY (CELL_ID) REFERENCES OCEAN_CELLULE(CELL_ID),
    FOREIGN KEY (RBC_ID) REFERENCES OCEAN_RNCBSC(RBC_ID),
    FOREIGN KEY (SYS_ID) REFERENCES OCEAN_SYSTEME(SYS_ID),
    FOREIGN KEY (ENV_ID) REFERENCES OCEAN_ENVIRONMNT(ENV_ID),
    FOREIGN KEY (TPC_ID) REFERENCES OCEAN_TYPCELL(TPC_ID),
    FOREIGN KEY (ZSE_ID) REFERENCES OCEAN_ZONESERVICE(ZSE_ID),
    FOREIGN KEY (ZVI_ID) REFERENCES OCEAN_ZONEVIE(ZVI_ID),
    FOREIGN KEY (ZRE_ID) REFERENCES OCEAN_ZONERESEAUX(ZRE_ID),
    FOREIGN KEY (ZSP_ID) REFERENCES OCEAN_ZONESPEC(ZSP_ID),
    FOREIGN KEY (CTR_ID) REFERENCES OCEAN_CONSTRUCTEUR(CTR_ID),
    FOREIGN KEY (ESW_ID) REFERENCES OCEAN_ETATSW(ESW_ID),
    FOREIGN KEY (SIT_ID) REFERENCES OCEAN_SITE(SIT_ID),
    FOREIGN KEY (OPP_ID) REFERENCES OCEAN_OPERATORAPPLIC(OPP_ID),
    FOREIGN KEY (RBC_ID2) REFERENCES OCEAN_RNCBSC(RBC_ID)
);

CREATE TABLE OCEAN_CONFBAIE (
    CFB_ID MEDIUMINT UNSIGNED NOT NULL PRIMARY KEY,
    CFB_SOURCEID MEDIUMINT UNSIGNED DEFAULT NULL,
    BAI_ID MEDIUMINT UNSIGNED NOT NULL,
    CHE_ID SMALLINT UNSIGNED DEFAULT NULL,
    CHE_MAXID SMALLINT UNSIGNED DEFAULT NULL,
    PUI_ID SMALLINT UNSIGNED NOT NULL,
    SYS_ID TINYINT UNSIGNED NOT NULL,
    CFB_CONFTRX VARCHAR(10) DEFAULT NULL,
    CFB_CONFTRXEDGE VARCHAR(10) DEFAULT NULL,
    CFB_CONFTRXHR VARCHAR(10) DEFAULT NULL,
    CFB_CONFMAXTRX VARCHAR(10) DEFAULT NULL,
    CFB_NONINST TINYINT UNSIGNED NOT NULL,
    CFB_COMMENT VARCHAR(250) NOT NULL,
    CFB_QUI VARCHAR(50) NOT NULL,
    CFB_QUAND DATETIME NOT NULL,
    CFB_VERSION TINYINT NOT NULL,
    CFB_CONFTWINTRX VARCHAR(10) DEFAULT NULL,
    CFB_CONFTRXEDGE_INST VARCHAR(10) DEFAULT NULL,
    CFB_CONFMCTRX VARCHAR(10) DEFAULT NULL,
    MRAD_ID SMALLINT UNSIGNED DEFAULT NULL,
    MRAD_GSM900 BOOLEAN DEFAULT NULL,
    MRAD_LTE1800 BOOLEAN NOT NULL,
    MRAD_GSM1800 BOOLEAN NOT NULL,
    MRAD_OPP BOOLEAN NOT NULL,
    CFB_TAC SMALLINT UNSIGNED DEFAULT NULL,
    CFB_TAC_IOT SMALLINT UNSIGNED DEFAULT NULL,
    CFB_TAC_BYT SMALLINT UNSIGNED DEFAULT NULL,
    CFB_TAC_IOT_BYT SMALLINT UNSIGNED DEFAULT NULL,

    FOREIGN KEY (CFB_SOURCEID) REFERENCES OCEAN_CONFBAIE(CFB_ID),
    FOREIGN KEY (BAI_ID) REFERENCES OCEAN_BAIE(BAI_ID),
    FOREIGN KEY (CHE_ID) REFERENCES OCEAN_CONFCHANNELELEM(CHE_ID),
    FOREIGN KEY (CHE_MAXID) REFERENCES OCEAN_CONFCHANNELELEM(CHE_ID),
    FOREIGN KEY (PUI_ID) REFERENCES OCEAN_CONFPUISSANCE(PUI_ID),
    FOREIGN KEY (SYS_ID) REFERENCES OCEAN_SYSTEME(SYS_ID),
    FOREIGN KEY (MRAD_ID) REFERENCES OCEAN_MODRADIO(MRAD_ID)
);

CREATE TABLE OCEAN_ODT_CFB (
    OTC_ID MEDIUMINT UNSIGNED NOT NULL PRIMARY KEY,
    CFB_ID MEDIUMINT UNSIGNED NOT NULL,
    ODT_ID MEDIUMINT UNSIGNED NOT NULL,
    OTC_FLAG TINYINT UNSIGNED NOT NULL,

    FOREIGN KEY (CFB_ID) REFERENCES OCEAN_CONFBAIE(CFB_ID),
    FOREIGN KEY (ODT_ID) REFERENCES OCEAN_OT(ODT_ID)
);

CREATE TABLE OCEAN_CFB_CELL (
    CCE_ID MEDIUMINT UNSIGNED NOT NULL PRIMARY KEY,
    CELL_ID INT UNSIGNED NOT NULL,
    CFB_ID MEDIUMINT UNSIGNED NOT NULL,
    CCE_QUAND DATETIME NOT NULL,

    FOREIGN KEY (CELL_ID) REFERENCES OCEAN_CELLULE(CELL_ID),
    FOREIGN KEY (CFB_ID) REFERENCES OCEAN_CONFBAIE(CFB_ID)
);

CREATE TABLE OCEAN_FREQUENCE2G (
    F2G_ID MEDIUMINT UNSIGNED NOT NULL PRIMARY KEY,
    PLN_ID SMALLINT UNSIGNED DEFAULT NULL,
    CELL_ID INT UNSIGNED NOT NULL,
    ESW_ID TINYINT UNSIGNED NOT NULL,
    SFQ_ID TINYINT UNSIGNED NOT NULL,
    F2G_NCC TINYINT UNSIGNED NOT NULL,
    F2G_BCC TINYINT UNSIGNED NOT NULL,
    F2G_HSN TINYINT DEFAULT NULL,
    F2G_RANG TINYINT UNSIGNED NOT NULL,
    F2G_CANAL SMALLINT UNSIGNED NOT NULL,
    F2G_FLGSUP BOOLEAN NOT NULL,
    F2G_NUMDI MEDIUMINT UNSIGNED DEFAULT NULL,
    F2G_QUI VARCHAR(50) NOT NULL,
    F2G_QUAND DATETIME NOT NULL,
    F2G_VERSION TINYINT NOT NULL,
    F2G_MAIO TINYINT UNSIGNED DEFAULT NULL,

    FOREIGN KEY (CELL_ID) REFERENCES OCEAN_CELLULE(CELL_ID),
    FOREIGN KEY (ESW_ID) REFERENCES OCEAN_ETATSW(ESW_ID),
    FOREIGN KEY (SFQ_ID) REFERENCES OCEAN_SAUTFRQ(SFQ_ID)
);

CREATE TABLE OCEAN_MODANT (
    MDA_ID INT UNSIGNED NOT NULL PRIMARY KEY,
    MDA_SOURCEID INT UNSIGNED DEFAULT NULL,
    RFT_ID SMALLINT UNSIGNED DEFAULT NULL,
    RFD_ID SMALLINT UNSIGNED DEFAULT NULL,
    FCA_ID TINYINT UNSIGNED NOT NULL,
    ANT_ID INT UNSIGNED NOT NULL,
    REP_ID SMALLINT UNSIGNED DEFAULT NULL,
    BTE_ID TINYINT UNSIGNED DEFAULT NULL,
    SYS_ID TINYINT UNSIGNED NOT NULL,
    MDA_ROS FLOAT(5,2) DEFAULT NULL,
    MDA_REPART SMALLINT UNSIGNED NOT NULL,
    MDA_PERTEUL FLOAT(5,2) NOT NULL,
    MDA_PERTEDL FLOAT(5,2) NOT NULL,
    MDA_G2RPILOT VARCHAR(10) DEFAULT NULL,
    MDA_CIPILOT INT DEFAULT NULL,
    MDA_NBBTE TINYINT UNSIGNED DEFAULT NULL,
    MDA_TMA BOOLEAN NOT NULL,
    MDA_DUPLEX BOOLEAN NOT NULL,
    MDA_DIPLEX BOOLEAN NOT NULL,
    MDA_NONINST TINYINT UNSIGNED NOT NULL,
    MDA_COMMENT VARCHAR(250) NOT NULL,
    MDA_QUI VARCHAR(50) NOT NULL,
    MDA_QUAND DATETIME NOT NULL,
    MDA_VERSION SMALLINT NOT NULL,
    TLT_ID SMALLINT UNSIGNED DEFAULT NULL,
    TPC_ID TINYINT UNSIGNED DEFAULT NULL,
    MDA_FEED BOOLEAN NOT NULL,
    MDA_FIPRO BOOLEAN NOT NULL,
    RET_ID TINYINT UNSIGNED DEFAULT NULL,
    MDA_RET BOOLEAN NOT NULL,
    REP_ID_1 SMALLINT UNSIGNED DEFAULT NULL,
    MDA_G2RPILOT_1 VARCHAR(10) DEFAULT NULL,
    MDA_CIPILOT_1 INT DEFAULT NULL,
    TPC_ID_1 TINYINT UNSIGNED DEFAULT NULL,
    MDA_MIMO BOOLEAN NOT NULL,
    MDA_SANTE BOOLEAN DEFAULT NULL,
    MDA_ATTENUATEUR BOOLEAN DEFAULT NULL,
    MDA_ATTENUATION TINYINT UNSIGNED DEFAULT NULL,
    RMM_ID TINYINT UNSIGNED DEFAULT NULL,

    FOREIGN KEY (MDA_SOURCEID) REFERENCES OCEAN_MODANT(MDA_ID),
    FOREIGN KEY (RFT_ID) REFERENCES OCEAN_REFTMA(RFT_ID),
    FOREIGN KEY (RFD_ID) REFERENCES OCEAN_REFDITRIPLEX(RFD_ID),
    FOREIGN KEY (FCA_ID) REFERENCES OCEAN_FCTANT(FCA_ID),
    FOREIGN KEY (ANT_ID) REFERENCES OCEAN_ANTENNE(ANT_ID),
    FOREIGN KEY (REP_ID) REFERENCES OCEAN_REPETEUR(REP_ID),
    FOREIGN KEY (BTE_ID) REFERENCES OCEAN_BIASTEE(BTE_ID),
    FOREIGN KEY (SYS_ID) REFERENCES OCEAN_SYSTEME(SYS_ID),
    FOREIGN KEY (MDA_G2RPILOT) REFERENCES OCEAN_SITE(SIT_NUMG2R),
    FOREIGN KEY (TLT_ID) REFERENCES OCEAN_TILTEL(TLT_ID),
    FOREIGN KEY (TPC_ID) REFERENCES OCEAN_TYPCELL(TPC_ID),
    FOREIGN KEY (RET_ID) REFERENCES OCEAN_REFRET(RET_ID),
    FOREIGN KEY (REP_ID_1) REFERENCES OCEAN_REPETEUR(REP_ID),
    FOREIGN KEY (MDA_G2RPILOT_1) REFERENCES OCEAN_SITE(SIT_NUMG2R),
    FOREIGN KEY (TPC_ID_1) REFERENCES OCEAN_TYPCELL(TPC_ID)
);

CREATE TABLE OCEAN_FEEDER (
    FEE_ID MEDIUMINT UNSIGNED NOT NULL PRIMARY KEY,
    FEE_SOURCEID MEDIUMINT UNSIGNED DEFAULT NULL,
    CTF_ID TINYINT UNSIGNED NOT NULL,
    TSC_IDFA TINYINT UNSIGNED DEFAULT NULL,
    TSC_IDFB TINYINT UNSIGNED DEFAULT NULL,
    FCF_ID TINYINT UNSIGNED DEFAULT NULL,
    FEE_LONG FLOAT(6,2) NOT NULL,
    FEE_PRTCBL FLOAT(5,2) DEFAULT NULL,
    FEE_LGBTFA FLOAT(5,2) DEFAULT NULL,
    FEE_LGBTFB FLOAT(5,2) DEFAULT NULL,
    FEE_COMMENT VARCHAR(250) NOT NULL,
    FEE_NONINST BOOLEAN NOT NULL,
    FEE_QUI VARCHAR(50) NOT NULL,
    FEE_QUAND DATETIME NOT NULL,
    FEE_VERSION TINYINT NOT NULL,
    MDA_ID INT UNSIGNED NOT NULL,

    FOREIGN KEY (FEE_SOURCEID) REFERENCES OCEAN_FEEDER(FEE_ID),
    FOREIGN KEY (MDA_ID) REFERENCES OCEAN_MODANT(MDA_ID)
);

CREATE TABLE OCEAN_ODT_MDA (
    OMA_ID MEDIUMINT UNSIGNED NOT NULL PRIMARY KEY,
    ODT_ID MEDIUMINT UNSIGNED NOT NULL,
    MDA_ID INT UNSIGNED NOT NULL,
    OMA_FLAG TINYINT UNSIGNED NOT NULL,

    FOREIGN KEY (ODT_ID) REFERENCES OCEAN_OT(ODT_ID),
    FOREIGN KEY (MDA_ID) REFERENCES OCEAN_MODANT(MDA_ID)
);

CREATE TABLE OCEAN_MDA_CELL (
    MCE_ID MEDIUMINT UNSIGNED NOT NULL PRIMARY KEY,
    CELL_ID INT UNSIGNED NOT NULL,
    MDA_ID INT UNSIGNED NOT NULL,
    MCE_QUAND DATETIME NOT NULL,

    FOREIGN KEY (CELL_ID) REFERENCES OCEAN_CELLULE(CELL_ID),
    FOREIGN KEY (MDA_ID) REFERENCES OCEAN_MODANT(MDA_ID)
);